[package]
name = "classicube-cef-plugin"
version = "1.9.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
async-dispatcher = { git = "https://github.com/SpiralP/rust-async-dispatcher.git" }
async-recursion = "1"
backtrace = "0.3"
base64 = "0.21"
bincode = "1"
clap = { git = "https://github.com/SpiralP/rust-clap-classicube.git", features = [
    "derive",
] }
classicube-helpers = { git = "https://github.com/SpiralP/rust-classicube-helpers.git" }
classicube-sys = { git = "https://github.com/SpiralP/rust-classicube-sys.git" }
deunicode = "1"
error-chain = "0.12"
futures = "0.3"
futures-timer = "3"
lazy_static = "1"
nalgebra = "0.30"
ncollide3d = "0.33"
rand = "0.8"
regex = "1"
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-flame = "0.2"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2"

[build-dependencies]
bindgen = "0.68"
cmake = "0.1"

[features]
ci = []


[package.metadata.release]
pre-release-commit-message = "Release {{version}}"
tag-message = "Release version {{version}}"
