[package]
name = "classicube-cef-plugin"
version = "0.5.7"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-dispatcher = { git = "https://github.com/SpiralP/rust-async-dispatcher.git" }
async-std = "1.5.0"
base64 = "0.12.0"
bincode = "1.2.1"
classicube-helpers = { git = "https://github.com/SpiralP/rust-classicube-helpers.git", features = ["futures"] }
classicube-sys = { git = "https://github.com/SpiralP/rust-classicube-sys.git" }
color-backtrace = { git = "https://github.com/SpiralP/color-backtrace-msgbox.git" }
error-chain = "0.12.2"
futures = "0.3.4"
invidious = { git = "https://github.com/SpiralP/rust-invidious.git" }
lazy_static = "1.4.0"
log = "0.4.8"
nalgebra = "0.21.0"
# at end of april they will update nalgebra in release
ncollide3d = { git = "https://github.com/rustsim/ncollide.git", branch = "simba" }
regex = "1.3.7"
serde = { version = "1.0.106", features = ["derive"] }
simplelog = "0.7.5"
tokio = { version = "0.2.18", features = ["full"] }
url = "2.1.1"
widestring = "0.4.0"

[build-dependencies]
bindgen = "0.53.2"
cmake = "0.1.42"
