[package]
name = "classicube-cef-plugin"
version = "0.12.2"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-dispatcher = { git = "https://github.com/SpiralP/rust-async-dispatcher.git" }
async-recursion = "0.3.1"
base64 = "0.12.3"
bincode = "1.3.1"
# chrono = { version = "0.4.11", features = ["serde"] }
clap = { git = "https://github.com/SpiralP/clap-cc.git" }
classicube-helpers = { git = "https://github.com/SpiralP/rust-classicube-helpers.git", features = ["futures"] }
classicube-sys = { git = "https://github.com/SpiralP/rust-classicube-sys.git" }
color-backtrace = { git = "https://github.com/SpiralP/color-backtrace-msgbox.git" }
detour = { git = "https://github.com/SpiralP/detour-rs.git" }
deunicode = "1.1.1"
error-chain = "0.12.2"
futures = "0.3.5"
futures-timer = "3.0.2"
invidious = { git = "https://github.com/SpiralP/rust-invidious.git" }
lazy_static = "1.4.0"
log = "0.4.11"
nalgebra = "0.21.1"
ncollide3d = "0.23.2"
rand = "0.7.3"
regex = "1.3.9"
serde = { version = "1.0.114", features = ["derive"] }
simplelog = "0.8.0"
# sntpc = "0.2.0"
tokio = { version = "0.2.21", features = ["full"] }
url = "2.1.1"
# widestring = "0.4.2"

[build-dependencies]
bindgen = "0.54.1"
cmake = "0.1.44"

[features]
ci = []



# remove when 1.1.8 releases
[patch."https://github.com/SpiralP/rust-classicube-sys.git"]
classicube-sys = { git = "https://github.com/SpiralP//rust-classicube-sys", branch = "next" }
