[package]
name = "classicube-cef"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

# [lib]
# crate-type = ["cdylib"]

[build-dependencies]
cmake = "0.1"

[dependencies]
classicube-sys = { git = "https://github.com/SpiralP/rust-classicube-sys.git" }
