[package]
name = "classicube-cef-plugin"
version = "1.1.2-alpha"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
async-dispatcher = { git = "https://github.com/SpiralP/rust-async-dispatcher.git" }
async-recursion = "0.3"
backtrace = "0.3"
base64 = "0.13"
bincode = "1"
clap = { git = "https://github.com/SpiralP/clap-cc.git" }
classicube-helpers = { git = "https://github.com/SpiralP/rust-classicube-helpers.git", features = ["futures"] }
classicube-sys = { git = "https://github.com/SpiralP/rust-classicube-sys.git" }
deunicode = "1"
error-chain = "0.12"
futures = "0.3"
futures-timer = "3"
lazy_static = "1"
nalgebra = "0.23"
ncollide3d = "0.26"
rand = "0.7"
regex = "1"
reqwest = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "0.2", features = ["full"] }
tracing = "0.1.22"
tracing-appender = "0.1.1"
tracing-flame = "0.1.0"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.15"
url = "2"

[build-dependencies]
bindgen = "0.56"
cmake = "0.1"

[features]
ci = []


[package.metadata.release]
disable-publish = true
tag-message = "Release version {{version}}"
pre-release-commit-message = "Release {{version}}"
post-release-commit-message = "Begin {{next_version}}"
dev-version-ext = "alpha"
