# use static c runtime so we can support older windows versions
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

# help both ./cef/cef and ./plugins/plugin.so find libcef.so
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-Wl,-rpath,$ORIGIN/../cef/cef_binary"]

[target.i686-unknown-linux-gnu]
rustflags = ["-C", "link-args=-Wl,-rpath,$ORIGIN/../cef/cef_binary"]

[target.armv7-unknown-linux-gnueabihf]
rustflags = ["-C", "link-args=-Wl,-rpath,$ORIGIN/../cef/cef_binary"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-Wl,-rpath,$ORIGIN/../cef/cef_binary"]

# tell mac to use symbols already loaded (from ClassiCube)
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-undefined dynamic_lookup"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-undefined dynamic_lookup"]
