name: Rust
on: [push]

jobs:
  windows:
    name: Build Windows ${{ matrix.config.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64, bits: 64 }
          - { arch: i686, bits: 32 }

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          iwr -useb get.scoop.sh | iex
          echo "##[add-path]$HOME\scoop\shims"
          echo "##[add-path]C:\ProgramData\scoop\shims"
          scoop install aria2
          scoop install --arch ${{ matrix.config.bits }}bit llvm
          echo "::set-env name=LIBCLANG_PATH::$HOME\scoop\apps\llvm\current\bin"
          aria2c 'http://opensource.spotify.com/cefbuilds/cef_binary_81.2.17%2Bgb382c62%2Bchromium-81.0.4044.113_windows${{ matrix.config.bits }}.tar.bz2' -o cef_binary.tar.bz2
          7z x -y 'cef_binary.tar.bz2'
          Remove-Item 'cef_binary.tar.bz2'
          7z x -y 'cef_binary.tar'
          Remove-Item 'cef_binary.tar'
          Get-ChildItem 'cef_binary_*' | Rename-Item -NewName 'cef_binary'
          Move-Item -Path 'cef_binary' -Destination 'cef_interface'

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.config.arch }}-pc-windows-msvc
          toolchain: nightly-${{ matrix.config.arch }}-pc-windows-msvc
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          target: ${{ matrix.config.arch }}-pc-windows-msvc
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          target: ${{ matrix.config.arch }}-pc-windows-msvc
          command: test
          args: -- --nocapture

      - name: Build Release
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          target: ${{ matrix.config.arch }}-pc-windows-msvc
          command: build
          args: --release

      - run: Rename-Item -Path "target\release\classicube_cef_plugin.dll" -NewName "classicube_cef_windows_${{ matrix.config.arch }}.dll"
        if: startsWith(github.ref, 'refs/tags/')

      - run: Get-ChildItem "target\release\build\classicube-cef-plugin-*\out\cefsimple.exe" | Rename-Item -NewName "cefsimple-${{ matrix.config.arch }}.exe"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/classicube_cef_windows_${{ matrix.config.arch }}.dll
            target/release/build/classicube-cef-plugin-*/out/cefsimple-${{ matrix.config.arch }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux:
    name: Build Linux ${{ matrix.config.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64, bits: 64 }
          # I don't want to figure out the dependencies on 32 bit linux
          # - { arch: i686, bits: 32 }

    steps:
      - uses: actions/checkout@v2

      - name: Install 64 bit deps
        if: matrix.config.bits == 64
        run: |
          sudo apt-get update \
          && sudo apt-get install -y git curl gcc g++ build-essential libssl-dev pkg-config libglib2.0-dev libpango1.0-dev \
            libatk1.0-dev libgdk-pixbuf2.0-dev libgtk-3-dev cmake clang libnss3 libasound2 libxss1 libnspr4 \
          && curl 'http://opensource.spotify.com/cefbuilds/cef_binary_81.2.17%2Bgb382c62%2Bchromium-81.0.4044.113_linux${{ matrix.config.bits }}.tar.bz2' | tar -xjf - \
          && mv cef_binary_* cef_interface/cef_binary

      - name: Install 32 bit deps
        if: matrix.config.bits == 32
        run: |
          sudo dpkg --add-architecture i386 \
          && sudo apt-get update \
          && sudo apt-get install -y git curl gcc g++ build-essential libssl-dev:i386 pkg-config libglib2.0-dev libpango1.0-dev \
            libatk1.0-dev libgdk-pixbuf2.0-dev libgtk-3-dev cmake libclang-dev libnss3 libasound2 libxss1 libnspr4 \
          && curl 'http://opensource.spotify.com/cefbuilds/cef_binary_81.2.17%2Bgb382c62%2Bchromium-81.0.4044.113_linux${{ matrix.config.bits }}.tar.bz2' | tar -xjf - \
          && mv cef_binary_* cef_interface/cef_binary

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.config.arch }}-unknown-linux-gnu
          toolchain: nightly-${{ matrix.config.arch }}-unknown-linux-gnu
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          target: ${{ matrix.config.arch }}-unknown-linux-gnu
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          target: ${{ matrix.config.arch }}-unknown-linux-gnu
          command: test
          args: -- --nocapture

      - name: Build Release
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          target: ${{ matrix.config.arch }}-unknown-linux-gnu
          command: build
          args: --release

      - run: mv target/release/libclassicube_cef_plugin.so "classicube_cef_linux_${{ matrix.config.arch }}.so"
        if: startsWith(github.ref, 'refs/tags/')

      - run: mv target/release/build/classicube-cef-plugin-*/out/cefsimple "cefsimple-linux-${{ matrix.config.arch }}"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            classicube_cef_linux_${{ matrix.config.arch }}.so
            cefsimple-linux-${{ matrix.config.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mac:
    name: Build MacOS ${{ matrix.config.arch }}
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64, bits: 64 }
          # cef-binary doesn't have 32 bit download
          # - { arch: i686, bits: 32 }

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          brew install cmake \
          && curl 'http://opensource.spotify.com/cefbuilds/cef_binary_81.2.17%2Bgb382c62%2Bchromium-81.0.4044.113_macosx${{ matrix.config.bits }}.tar.bz2' | tar -xjf - \
          && mv cef_binary_* cef_interface/cef_binary

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.config.arch }}-apple-darwin
          toolchain: nightly-${{ matrix.config.arch }}-apple-darwin
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          target: ${{ matrix.config.arch }}-apple-darwin
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          target: ${{ matrix.config.arch }}-apple-darwin
          command: test
          args: -- --nocapture

      - name: Build Release
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          target: ${{ matrix.config.arch }}-apple-darwin
          command: build
          args: --release

      - run: mv target/release/libclassicube_cef_plugin.dylib "classicube_cef_macos_${{ matrix.config.arch }}.dylib"
        if: startsWith(github.ref, 'refs/tags/')

      - run: |
          mv target/release/build/classicube-cef-plugin-*/out/cefsimple.app . \
          && tar -cvf - cefsimple.app/ | gzip - > "cefsimple-macos-${{ matrix.config.arch }}.tar.gz"
        if: startsWith(github.ref, 'refs/tags/')
      # - name: Upload Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: |
      #       classicube_cef_macos_${{ matrix.config.arch }}.dylib
      #       cefsimple-macos-${{ matrix.config.arch }}.tar.gz
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
