name: Rust
on: [push]

jobs:
  windows:
    name: Build Windows ${{ matrix.config.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64, bits: 64 }
          - { arch: i686, bits: 32 }

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          iwr -useb get.scoop.sh | iex
          echo "##[add-path]$HOME\scoop\shims"
          echo "##[add-path]C:\ProgramData\scoop\shims"
          scoop install aria2
          scoop install --arch ${{ matrix.config.bits }}bit llvm
          echo "::set-env name=LIBCLANG_PATH::$HOME\scoop\apps\llvm\current\bin"
          aria2c 'http://opensource.spotify.com/cefbuilds/cef_binary_84.3.3%2Bgffc2f0e%2Bchromium-84.0.4147.89_windows${{ matrix.config.bits }}.tar.bz2' -o cef_binary.tar.bz2
          7z x -y 'cef_binary.tar.bz2'
          Remove-Item 'cef_binary.tar.bz2'
          7z x -y 'cef_binary.tar'
          Remove-Item 'cef_binary.tar'
          Get-ChildItem 'cef_binary_*' | Rename-Item -NewName 'cef_binary'
          Move-Item -Path 'cef_binary' -Destination 'cef_interface'

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.config.arch }}-pc-windows-msvc
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          command: test
          args: --features ci -- --nocapture

      - name: Build Release
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          command: build
          args: --release

      - run: Rename-Item -Path "target\release\classicube_cef_plugin.dll" -NewName "classicube_cef_windows_${{ matrix.config.arch }}.dll"
        if: startsWith(github.ref, 'refs/tags/')

      - run: Rename-Item -Path "target\release\classicube_cef_plugin.pdb" -NewName "classicube_cef_windows_${{ matrix.config.arch }}.pdb"
        if: startsWith(github.ref, 'refs/tags/')

      - run: Get-ChildItem "target\release\build\classicube-cef-plugin-*\out\cef.exe" | Rename-Item -NewName "cef-windows-${{ matrix.config.arch }}.exe"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/classicube_cef_windows_${{ matrix.config.arch }}.dll
            target/release/classicube_cef_windows_${{ matrix.config.arch }}.pdb
            target/release/build/classicube-cef-plugin-*/out/cef-windows-${{ matrix.config.arch }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux_x86:
    name: Build Linux ${{ matrix.config.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64 }
          - { arch: i686 }
          # - { arch: armhf, target: armv7-unknown-linux-gnueabihf }
          # - { arch: aarch64, target: aarch64-unknown-linux-gnu }

    steps:
      - uses: actions/checkout@v2

      - name: Install x86_64 deps
        if: ${{ matrix.config.arch == 'x86_64' }}
        run: |
          sudo apt-get -y update \
          && sudo apt-get -y install git curl gcc g++ build-essential cmake clang-10 pkg-config \
            libssl-dev libglib2.0-dev libpango1.0-dev libatk1.0-dev libgtk-3-dev libgdk-pixbuf2.0-dev \
            libnss3 libasound2 libxss1 libnspr4 \
          && curl 'http://opensource.spotify.com/cefbuilds/cef_binary_84.3.3%2Bgffc2f0e%2Bchromium-84.0.4147.89_linux64.tar.bz2' | tar -xjf - \
          && mv cef_binary_* cef_interface/cef_binary

      - name: Install i686 deps
        if: ${{ matrix.config.arch == 'i686' }}
        run: |
          sudo dpkg --add-architecture i386 \
          && sudo apt-get -y update \
          && sudo apt-get -y install git curl gcc g++ build-essential cmake clang-10 pkg-config:i386 \
            gcc-multilib g++-multilib \
            libssl-dev:i386 libglib2.0-dev:i386 libpango1.0-dev:i386 libatk1.0-dev:i386 libgtk-3-dev:i386 libgdk-pixbuf2.0-dev:i386 \
            libnss3:i386 libasound2:i386 libxss1:i386 libnspr4:i386 \
          && curl 'http://opensource.spotify.com/cefbuilds/cef_binary_84.3.3%2Bgffc2f0e%2Bchromium-84.0.4147.89_linux32.tar.bz2' | tar -xjf - \
          && mv cef_binary_* cef_interface/cef_binary \
          && echo "::set-env name=PKG_CONFIG_ALLOW_CROSS::1"

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.config.arch }}-unknown-linux-gnu
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          command: test
          args: --features ci -- --nocapture

      - name: Build Release
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          command: build
          args: --release

      - run: mv target/release/libclassicube_cef_plugin.so "classicube_cef_linux_${{ matrix.config.arch }}.so"
        if: startsWith(github.ref, 'refs/tags/')

      - run: mv target/release/build/classicube-cef-plugin-*/out/cef "cef-linux-${{ matrix.config.arch }}"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            classicube_cef_linux_${{ matrix.config.arch }}.so
            cef-linux-${{ matrix.config.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mac:
    name: Build MacOS ${{ matrix.config.arch }}
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64, bits: 64 }
          # cef-binary doesn't have 32 bit download
          # - { arch: i686, bits: 32 }

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          brew install cmake \
          && curl 'http://opensource.spotify.com/cefbuilds/cef_binary_84.3.3%2Bgffc2f0e%2Bchromium-84.0.4147.89_macosx${{ matrix.config.bits }}.tar.bz2' | tar -xjf - \
          && mv cef_binary_* cef_interface/cef_binary

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.config.arch }}-apple-darwin
          toolchain: nightly-${{ matrix.config.arch }}-apple-darwin
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          command: test
          args: --features ci -- --nocapture

      - name: Build Release
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          command: build
          args: --release

      - run: mv target/release/libclassicube_cef_plugin.dylib "classicube_cef_macos_${{ matrix.config.arch }}.dylib"
        if: startsWith(github.ref, 'refs/tags/')

      - run: mv target/release/build/classicube-cef-plugin-*/out/cef "cef-macos-${{ matrix.config.arch }}"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            classicube_cef_macos_${{ matrix.config.arch }}.dylib
            cef-macos-${{ matrix.config.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
